import clsx from 'clsx'
import type { Metadata } from 'next'
import { Figtree, Roboto_Serif } from 'next/font/google'
import './globals.css'

const robotoSerif = Roboto_Serif({ subsets: ['latin'], variable: '--serif' })
const figtree = Figtree({ subsets: ['latin'], variable: '--sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(robotoSerif.variable, figtree.variable, 'font-sans')}>{children}</body>
    </html>
  )
}
